### PR TITLE
Update locales for both Chinese & English

### PR DESCRIPTION
**Pull request by tainewoo**
1. update Chinese locales to fix some wrong translations and add new operators.
2. update English locales to fix one typo.

### CODE REVIEW

**Comment by tainewoo** [comment]
Hi @HugoHasenbein 

I created a PR to fix some Chinese translation issue and add translations for new operators, and fix an English typo.

**Review by HugoHasenbein — APPROVED** [review]

**Comment by HugoHasenbein** [comment]
Dear Taine,

I approved the translations,for which I thank.

With respect to the alias_method replacements: did you test redmine_more_filters with redmine 4.x?

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

Yes my platform is Redmine4.x, so I have to update the alias_method_chain to alias_method because the alias_method_chain is obsoleted by rails.
But because I don't have Redmine3.x to test with the alias_method, and that's most of users who are using this plugin, and it's also your platform, so I just create the PR for alias_method and let you know about it.
You can leave it there in case some day you need it, or maybe someday someone who is using the Redmine4.x they can find this fix to fix it locally, or maybe using my folk is ok too. 
It's ok you don't merge it for code safe. I can update the codes again and create new PR for that if someday you add more alias_method_chain in this plugin.

**Comment by tainewoo** [comment]
it's happy to be a contributor~

**Comment by HugoHasenbein** [comment]
Dear Taine,

You are welcome :-)

Try redmine_more_filters version 1.3.0 - supporting both, redmine 3+ and redmine 4+ - It will need some testing though. I am not aware, if this version collides with other redmine 4.0 plugins.

Merry Christmas

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

sorry just read this, thank you for your help and Merry Christmas

**Pull request merged**
